title : Riley Wilson
name: 'Riley Wilson'
description: 'blog'

markdown: kramdown
highlighter: rouge
javascript_enabled: false


collections:
  posts:
    title: Essays
    default_open: true
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Essays
      permalink: /post/:title


plugins:
  - jekyll-sitemap
